version: '3'

services:
  redis:
    image: redis:6-alpine
  web:
    depends_on:
      - redis
    image: siibra-toolbox-template-server:local-dev
    build:
      context: .
      dockerfile: ./http.server.dockerfile
    environment:
      SIIBRA_TOOLBOX_CELERY_BROKER: redis://redis:6379
      SIIBRA_TOOLBOX_CELERY_RESULT: redis://redis:6379
    ports:
      - "6001:6001"
  worker:
    depends_on:
      - redis
    image: siibra-toolbox-template-worker:local-dev
    build:
      context: .
      dockerfile: ./http.worker.dockerfile
    environment:
      SIIBRA_TOOLBOX_CELERY_BROKER: redis://redis:6379
      SIIBRA_TOOLBOX_CELERY_RESULT: redis://redis:6379